spring.application.name=learn-spring-boot
logging.level.org.springframework=trace
spring.profiles.active=prod

currency-service.url=http://default.in28Minutes.com
currency-service.username=default-user
currency-service.password=default-pass
