spring.application.name=restful-web-services
logging.level.org.springframework=info
management.endpoints.web.exposure.include=*

#spring.mvc.apiversion.use.path-segment=0

#spring.mvc.apiversion.use.query-parameter=ver

#spring.mvc.apiversion.use.header=X-API-VERSION

##Accept:application/json;ver=2
#spring.mvc.apiversion.use.media-type-parameter[application/json]=ver